# Replace your render.yaml
cat > render.yaml << 'EOF'
services:
  - type: web
    name: snipsnap
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php -S 0.0.0.0:8000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
EOF
